<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1725;CA2016</NoWarn>
  </PropertyGroup>

  <ItemGroup><PackageReference Include="MongoDB.Driver" Version="2.30.0" /></ItemGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Timesheet.Application\Timesheet.Application.csproj" />
    <ProjectReference Include="..\Timesheet.Domain\Timesheet.Domain.csproj" />
  </ItemGroup>
</Project>
